# /* wallust template - colors-hyprland */ 

$background = rgb(2D2D2D)
$foreground = rgb(EEF1F3)
$color0 = rgb(525252)
$color1 = rgb(9FA0AA)
$color2 = rgb(84AAAD)
$color3 = rgb(A5B5C2)
$color4 = rgb(BABECA)
$color5 = rgb(B2CACC)
$color6 = rgb(CFD6DE)
$color7 = rgb(DFE2E6)
$color8 = rgb(9C9EA1)
$color9 = rgb(9FA0AA)
$color10 = rgb(84AAAD)
$color11 = rgb(A5B5C2)
$color12 = rgb(BABECA)
$color13 = rgb(B2CACC)
$color14 = rgb(CFD6DE)
$color15 = rgb(DFE2E6)
